### ISSUE TITLE
گزارش فاز 1

### ISSUE THREAD

**Issue by NastaranZare** [amirrezasfr/pr2_gp4#14]

**Comment by amirrezasfr** [comment]
[PRJ2_4.docx](https://github.com/amirrezasfr/pr2_gp4/files/5742194/PRJ2_4.docx)
[PRJ2_4.docx](https://github.com/amirrezasfr/pr2_gp4/files/5742190/PRJ2_4.docx)

**Comment by amirrezasfr** [comment]
[Uploading PRJ2_4.pdf…]()
فایل پی دی اف فاز اول
