### ISSUE TITLE
بررسی نمودار مورد کاربرد

### ISSUE THREAD

**Issue by NastaranZare** [amirrezasfr/pr2_gp4#18]

**Comment by amirrezasfr** [comment]
نمودار بسیار عالی و با کیفیت بود و از نظر من هم مشکلی نداشت.

**Comment by NastaranZare** [comment]
![UseCaseDiagram vpd](https://user-images.githubusercontent.com/76446176/104204451-8cb24480-5442-11eb-8983-e4a1ef2a25bb.png)

**Comment by NastaranZare** [comment]
تغییرات چک شود
![UseCaseDiagram vpd (2)](https://user-images.githubusercontent.com/76446176/104206350-a6548b80-5444-11eb-9268-45c1f2341d32.png)
