### ISSUE TITLE
(مشخص کردن مشتریان ( کاربران هدف

### ISSUE THREAD

**Issue by amirrezasfr** [amirrezasfr/pr2_gp4#2]

**Comment by NastaranZare** [comment]
https://www.amar.org.ir/%D8%AF%D8%A7%D8%AF%D9%87%D9%87%D8%A7-%D9%88-%D8%A7%D8%B7%D9%84%D8%A7%D8%B9%D8%A7%D8%AA-%D8%A2%D9%85%D8%A7%D8%B1%DB%8C/%D9%87%D8%B2%DB%8C%D9%86%D9%87-%D9%88-%D8%AF%D8%B1%D8%A7%D9%85%D8%AF-%D8%AE%D8%A7%D9%86%D9%88%D8%A7%D8%B1/%D9%87%D8%B2%DB%8C%D9%86%D9%87-%D9%88-%D8%AF%D8%B1%D8%A7%D9%85%D8%AF-%DA%A9%D9%84-%DA%A9%D8%B4%D9%88%D8%B1

**Comment by NastaranZare** [comment]
https://startupfashion.com/8-questions-define-target-market/

**Comment by NastaranZare** [comment]
https://news.akhbarrasmi.com/news/13960808266124830/%DA%AF%D8%B2%D8%A7%D8%B1%D8%B4%DB%8C-%D8%A7%D8%B2-%D8%AE%D8%B1%DB%8C%D8%AF-%D8%A7%DB%8C%D9%86%D8%AA%D8%B1%D9%86%D8%AA%DB%8C-%D9%84%D8%A8%D8%A7%D8%B3-%D8%A8%D9%87-%D9%87%D9%85%D8%B1%D8%A7%D9%87-%D8%A7%DB%8C%D9%86%D9%81%D9%88%DA%AF%D8%B1%D8%A7%D9%81%DB%8C%DA%A9/
