### ISSUE TITLE
رسم نمودار توالی بوسیله‌ی نرم‌افزار ویژوال پارادایم

### ISSUE THREAD

**Issue by NastaranZare** [amirrezasfr/pr2_gp4#22]

**Comment by amirrezasfr** [comment]
![خرید مشتری (2)](https://user-images.githubusercontent.com/64785140/104108187-e8ac8a00-52d7-11eb-99e5-f6506a7e5572.PNG)
![ثبت نام پیک (1)](https://user-images.githubusercontent.com/64785140/104108191-eba77a80-52d7-11eb-8adc-3c7929c4445e.PNG)
![Uploading ثبت نام فروشگاه (1).PNG…]()

**Comment by amirrezasfr** [comment]
![ثبت نام مشتری (2)](https://user-images.githubusercontent.com/64785140/104108196-eea26b00-52d7-11eb-90d0-62b1e6102600.PNG)
